---
- hosts: 'localhost'
  tasks:
    - name: 'install bash from homebrew first'
      homebrew:
        name: 'bash'
    - block:
      - name: 'configure passwordless sudo'
        lineinfile:
          dest: '/etc/sudoers'
          regexp: '^%admin'
          line: '%admin ALL=(ALL) NOPASSWD: ALL'
          validate: '/usr/sbin/visudo -cf %s'
      - name: 'add custom bash'
        lineinfile:
          dest: '/etc/shells'
          line: '/usr/local/bin/bash'
      - name: 'change my default shell'
        command: 'chsh -s /usr/local/bin/bash squeeb'
      become: true
      ignore_errors: true
    - name: 'Install Homebrew Cask packages'
      homebrew_cask:
        name: '{{ item }}'
      with_items: '{{ homebrew_cask_packages }}'
      ignore_errors: true
    - name: 'Install Homebrew packages'
      homebrew:
        name: '{{ item.name }}'
        install_options: '{{ item.install_options|default() }}'
      with_items: '{{ homebrew_packages }}'
      ignore_errors: true
    - block:
      - name: 'Symlink Dotfiles'
        file:
          src: '{{ ansible_user_dir }}/Nextcloud/dotfiles/{{ item.path }}'
          dest: '{{ ansible_user_dir }}/{{ item.dest }}'
          state: 'link'
        with_items:
          - path: 'bash_profile'
            dest: '.bash_profile'
          - path: 'config'
            dest: '.config'
          - path: 'python'
            dest: '.python'
          - path: 'ssh'
            dest: '.ssh'
          - path: 'vim/vim'
            dest: '.vim'
          - path: 'vim/vimrc'
            dest: '.vimrc'
      - file:
          path: '{{ ansible_user_dir }}/{{ item.path }}'
          mode: '{{ item.mode }}'
        with_items:
          - path: '.ssh'
            mode: '0700'
          - path: '.ssh/id_rsa'
            mode: '0600'
      - file:
          path: '{{ ansible_user_dir }}/.local_config'
          state: 'directory'
      - copy:
          content: |
            Host *
              UseKeychain yes
          dest: '{{ ansible_user_dir }}/.local_config/ssh_config'

      tags: 'files'
      ignore_errors: true
    - name: 'set preferences'
      command: '{{ item }}'
      with_items: '{{ preferences }}'
      tags:
        - 'defaults'
        - 'preferences'
      ignore_errors: true
      notify: 'restart services'
    - name: 'get my uid'
      command: 'id -u'
      register: 'my_uid'
      tags: 'services'
      ignore_errors: true
    - name: 'stop stupid services'
      command: 'launchctl kill {{ item }}'
      tags: 'services'
      with_items:
        - 'system/com.apple.gamed'
      ignore_errors: true
      become: true
    - name: 'disable stupid services'
      command: 'launchctl disable {{ item }}'
      tags: 'services'
      with_items:
        - 'system/com.apple.gamed'
      ignore_errors: true
      become: true
    # - name: 'enable stupid services'
    #   command: 'launchctl disable {{ item }}'
    #   tags: 'services'
    #   with_items:
    #     - 'user/{{ my_uid.stdout }}/com.apple.photoanalysisd'
    #     - 'system/com.apple.iconservices.iconservicesd'
    #     - 'system/com.apple.iconservices.iconservicesagent'
    #   ignore_errors: true
    # - name: 'start stupid services'
    #   command: 'launchctl start {{ item }}'
    #   tags: 'services'
    #   with_items:
    #     - 'user/{{ my_uid.stdout }}/com.apple.photoanalysisd'
    #     - 'system/com.apple.iconservices.iconservicesd'
    #     - 'system/com.apple.iconservices.iconservicesagent'
    #   ignore_errors: true
    #   become: true
    - name: "unhide stuff that shouldn't be hidden"
      command: 'chflags nohidden {{ item }}'
      with_items:
        - '~/Library/'
      tags: 'unhide'
      ignore_errors: true
  vars:
    homebrew_packages:
      - name: 'vim'
        with_options: 'with-cscope,with-python,with-lua,override-system-vim'
      - name: 'htop'
      - name: 'bash-completion'
      - name: 'git'
      - name: 'hub'
      - name: 'iperf'
      - name: 'iperf3'
      - name: 'nmap'
      - name: 'ssh-copy-id'
      - name: 'readline'
      - name: 'pv'
      - name: 'wget'
      - name: 'irssi'
      - name: 'mtr'
      - name: 'jq'
      - name: 'kubectl'
      - name: 'vault'
      - name: 'openssl'
      - name: 'coreutils'
      - name: 'ipcalc'
      - name: 'minicom'
      - name: 'git-lfs'
      - name: 'graphviz'
      - name: 'bat'
      - name: 'tiger-vnc'
      - name: 'httpie'
      - name: 'cfssl'
      - name: 'ipmitool'
      - name: 'ipmiutil'
      - name: 'inetutils'
    homebrew_cask_packages:
      - 'wireshark'
      - 'macdown'
      - 'iterm2'
      - 'dropbox'
      - 'google-chrome'
      - 'virtualbox'
      - 'virtualbox-extension-pack'
      - 'vagrant'
      - 'spotify'
      - 'karabiner-elements'
      - 'macvim'
      - 'docker'
      - 'licecap'
      - 'sequel-pro'
      - 'skitch'
      - 'flux'
      - 'homebrew/cask-fonts/font-inconsolata'
      - 'homebrew/cask-fonts/font-inconsolata-for-powerline'
      - 'aerial'
      - 'boostnote'
      - 'tigervnc-viewer'
      - 'xquartz'
      - 'google-cloud-sdk'
      - 'homebrew/cask-drivers/prolific-pl2303'
      - 'paste'
      - 'vnc-viewer'
      - 'tunnelblick'
    homebrew_taps:
      - 'homebrew/cask-fonts'
      - 'homebrew/cask-drivers'
    mas_installed_apps:
      - id: 803453959
        name: "Slack"
      - id: 1384080005
        name: "Tweetbot 3 for Twitter"
      - id: 1278508951
        name: "Trello"
      - id: 406825478
        name: "Telephone"
      - id: 1295203466
        name: "Microsoft Remote Desktop 10"
      # - id: 412529613
      #   name: "Cinch"
      - id: 407963104
        name: "Pixelmator"
      - id: 425424353
        name: "The Unarchiver"
      - id: 405399194
        name: "Kindle"
      - id: 1333542190
        name: '1Password 7 - Password Manager'
      # - id: 1319778037
      #   name: 'iStat Menus'
      - id: 639968404
        name: 'Parcel - Delivery Tracking'
      - id: 1147396723
        name: 'WhatsApp Desktop'
      - id: 441258766
        name: 'Magnet'
    preferences:
      - 'defaults write com.apple.Safari IncludeInternalDebugMenu 1'
      - 'defaults write com.apple.finder AppleShowAllFiles FALSE'
      - 'defaults write -g ApplePressAndHoldEnabled -bool false'
      - 'defaults write com.apple.dock autohide-time-modifier -float 0.8'
      - 'defaults write com.apple.dock autohide-delay -float 0.05'
      - 'defaults write com.apple.ImageCapture disableHotPlug -bool true'
      - 'defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true'
      - 'defaults write NSGlobalDomain AppleShowAllExtensions -bool true'
  roles:
    - 'geerlingguy.mas'
  handlers:
    - name: 'restart services'
      command: 'killall {{ item }}'
      loop:
        - 'Finder'
        - 'Dock'
